.TH devilspie 1
.SH NAME
devilspie \- perform actions on windows as they are created

.SH SYNOPSIS
.B devilspie
.I "configuration-file"

.SH "DESCRIPTION"
.BR devilspie
is a program which can detect windows as they are created, and perform
actions on them if they match as set of criteria.

The configuration files are a set of s-expressions.  For documentation and
examples, see /usr/share/doc/devilspie/.

.SH BUGS
This manpage is useless, as it was thrown together on a train.

.SH AUTHOR
This manual page was written by Ross Burton <ross@burtonini.com>.
