#!/bin/sh
# devilspie postinst -- install the SGML catalogue

set -e

PACKAGE=devilspie
CENTRALCAT=/etc/sgml/${PACKAGE}.cat
ORDCATS="misc/devilspie/devilspie.cat"

if [ "$1" = configure ]; then
    for ordcat in ${ORDCATS}; do
        update-catalog --quiet --add ${CENTRALCAT} /usr/share/sgml/${ordcat}
    done
    update-catalog --quiet --add --super ${CENTRALCAT}
fi

#DEBHELPER#

exit 0
